import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://bw-niss.dev-k8s.bdv.local/');
  await page.getByRole('textbox', { name: 'Username' }).click();
  await page.waitForTimeout(1000);
  await page.getByRole('textbox', { name: 'Username' }).fill('niss_superuser_test');
  await page.getByRole('textbox', { name: 'Password' }).click();
  await page.getByRole('textbox', { name: 'Password' }).fill('Bdvoct@2025');
  await page.getByRole('button', { name: 'Sign In' }).click();
  await page.waitForTimeout(1000);
  await page.getByRole('link', { name: 'Dashboard' }).click();
  await page.waitForTimeout(1000);
  await page.getByRole('link', { name: 'All Transactions' }).click();
  await page.waitForTimeout(1000);
  await page.getByRole('button', { name: 'Incoming' }).click();
  await page.waitForTimeout(1000);
  await page.getByRole('link', { name: 'Create Transaction' }).first().click();
  await page.waitForTimeout(1000);
  await page.getByRole('link', { name: 'All Inward Transactions' }).click();
  await page.waitForTimeout(1000);
  await page.getByRole('link', { name: 'Customer Info Pending' }).click();
  await page.waitForTimeout(1000);
  await page.getByRole('link', { name: 'Pending Review' }).first().click();
  await page.waitForTimeout(1000);
  await page.getByRole('link', { name: 'Pending Approval' }).first().click();
  await page.waitForTimeout(1000);
  await page.getByRole('link', { name: 'Financial Processing' }).first().click();
  await page.waitForTimeout(1000);
  await page.getByRole('link', { name: 'Financial Processed' }).first().click();
  await page.waitForTimeout(1000);
  await page.getByRole('link', { name: 'Financial Failed' }).click();
  await page.waitForTimeout(1000);
  await page.getByRole('link', { name: 'Customer Repairs' }).click();
  await page.waitForTimeout(1000);
  await page.getByRole('link', { name: 'Terminated' }).click();
  await page.waitForTimeout(1000);
  await page.getByRole('button', { name: 'Incoming' }).click();
  await page.waitForTimeout(1000);
  await page.getByRole('button', { name: 'Outgoing' }).click();
  await page.waitForTimeout(1000);
  await page.getByRole('link', { name: 'Create Transaction' }).nth(1).click();
  await page.waitForTimeout(1000);
  await page.getByRole('link', { name: 'All Outward Transactions' }).click();
  await page.waitForTimeout(1000);
  await page.getByRole('link', { name: 'Pending Review' }).nth(1).click();
  await page.waitForTimeout(1000);
  await page.getByRole('link', { name: 'Pending Approval' }).nth(1).click();
  await page.waitForTimeout(1000);
  await page.getByRole('link', { name: 'Pending Liquidity' }).click();
  await page.waitForTimeout(1000);
  await page.getByRole('link', { name: 'Financial Processing' }).nth(1).click();
  await page.waitForTimeout(1000);
  await page.getByRole('link', { name: 'Financial Processed' }).nth(1).click();
  await page.waitForTimeout(1000);
  await page.getByRole('button', { name: 'Outgoing' }).click();
  await page.waitForTimeout(1000);
  await page.getByRole('button', { name: 'User Menu' }).click();
  await page.waitForTimeout(1000);
  await page.getByRole('menuitem', { name: 'Sign Out' }).click();
  await page.waitForTimeout(1000);
});